apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 30001
    targetPort: 30001
    nodePort: 30001
  selector:
    app: app
    tier: frontend
