apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: app
        tier: frontend
    spec:
      containers:
      - name: app
        image: isaoshinohara/tictactoeserver:4
        ports:
        - containerPort: 30001
