apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 30000
    targetPort: 6379
    nodePort: 30000
  selector:
    app: redis
    tier: backend
